title: "The Trait Modern"
author: "Max Tilley"
description: "Musing on Rust, and maybe some Python" # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
#email: "example@mail.com"
#twitter_username: "twitteruser"
github_username: "3tilley"
#linkedin_username: "linkedinuser"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
#remote_theme: "jekyll/minima"

theme: "minima"
rss: rss

kramdown:
  syntax_highlighter: rouge
  math_engine: mathjax

plugins:
  - jekyll-sitemap
  #- jekyll-remote-theme
  #- jekyll-feed

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other


google_analytics: G-W8MM0ES7PC
